/*ALTERA A TABELA ADICIONANDO UMA NOVA COLUNA*/
ALTER TABLE livro
ADD COLUMN status_leitura VARCHAR(255);

/*ALTERA A TABELA APAGANDO UMA COLUNA*/
ALTER TABLE livro
DROP COLUMN status_leitura;

DESCRIBE livro;

/*ALTERA A TABELA MODIFICANDO UMA COLUNA*/
ALTER TABLE livro
MODIFY COLUMN status_leitura BOOLEAN DEFAULT (11);


/*ALTERA A TABELA ADICIONANDO UMA NOVA RESTRIÇÃO A COLUNA*/
ALTER TABLE livro
ADD CONSTRAINT check_status_livro
CHECK (status_leitura IN (0,1));

/*DESCREVE A DESCRIÇÃO DA TABELA*/
DESCRIBE livro;

/*ADICIONANDO UMA FK COM ALTER*/
ALTER TABLE livro
ADD COLUMN id_usuario INT,
ADD CONSTRAINT fk_livro_usuari
FOREIGN KEY (id_usuario)
REFERENCES usuario(id_usuario)
ON DELETE CASCADE;
