/*ALTERANDO O TIPO DE DADO NA COLUNA data_cadastro*/
ALTER TABLE usuario
MODIFY data_cadastro TIMESTAMP;

/*ADICIONANDO UMA COLUNA NA TABELA USUARIO*/
ALTER TABLE usuario
ADD COLUMN data_atualizacao TIMESTAMP;