/*APAGANDO COLUNAS NA TABELA LIVRO*/
ALTER TABLE livro
DROP COLUMN autor,
DROP COLUMN editora,
DROP COLUMN categoria;

/*ADICIONANDO COLUNAS NA TABELA LIVRO*/
ALTER TABLE livro 
ADD COLUMN data_cadastro TIMESTAMP,
ADD COLUMN data_atualizacao TIMESTAMP,
ADD COLUMN lido BOOLEAN DEFAULT (0);

/*CRIANDO CHAVE ESTRANGEIRA COM RESTRIÇÃO CASCATA*/
ALTER TABLE livro
ADD COLUMN id_usuario INT,
ADD CONSTRAINT fk_livro_usuario
FOREIGN KEY (id_usuario)
REFERENCES usuario(id_usuario)
ON DELETE CASCADE;

/*CRIANDO CHAVE ESTRANGEIRA COM RESTRIÇÃO RESTRICT*/
ALTER TABLE livro
ADD COLUMN id_autor INT,
ADD CONSTRAINT fk_livro_autor
FOREIGN KEY (id_autor)
REFERENCES Autor(id_autor)
ON DELETE RESTRICT;

/*CRIANDO CHAVE ESTRANGEIRA COM RESTRIÇÃO RESTRICT*/
ALTER TABLE livro
ADD COLUMN id_editora INT,
ADD CONSTRAINT fk_livro_editora
FOREIGN KEY (id_editora)
REFERENCES Editora(id_editora)
ON DELETE RESTRICT;

/*CRIANDO CHAVE ESTRANGEIRA COM RESTRIÇÃO RESTRIC*/
ALTER TABLE livro
ADD COLUMN id_categoria INT,
ADD CONSTRAINT fk_livro_categoria
FOREIGN KEY (id_categoria)
REFERENCES Categoria(id_categoria)
ON DELETE RESTRICT;